# Project: lotto3_linked-list
# Makefile created by Dev-C++ 5.8.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = lotto3_main.o lotto3_util.o
LINKOBJ  = lotto3_main.o lotto3_util.o
LIBS     = -L"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/lib32" -L"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = lotto3_linked-list.exe
CXXFLAGS = $(CXXINCS) -march=native -O3 -m32
CFLAGS   = $(INCS) -march=native -O3 -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

lotto3_main.o: lotto3_main.cpp
	$(CPP) -c lotto3_main.cpp -o lotto3_main.o $(CXXFLAGS)

lotto3_util.o: lotto3_util.cpp
	$(CPP) -c lotto3_util.cpp -o lotto3_util.o $(CXXFLAGS)
