# Project: lotto3
# Makefile created by Dev-C++ 5.8.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = lotto3_main.o lotto3_utils.o
LINKOBJ  = lotto3_main.o lotto3_utils.o
LIBS     = -L"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/lib32" -L"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/ikaros/Desktop/Programs/Dev-Cpp Portable/32位元/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = lotto3.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

lotto3_main.o: lotto3_main.cpp
	$(CPP) -c lotto3_main.cpp -o lotto3_main.o $(CXXFLAGS)

lotto3_utils.o: lotto3_utils.cpp
	$(CPP) -c lotto3_utils.cpp -o lotto3_utils.o $(CXXFLAGS)
